# spring.data.mongodb.uri=mongodb+srv://mathoanghon18112000:hoainam12@cluster0.mvwile5.mongodb.net/
spring.data.mongodb.uri=mongodb+srv://admin:admin@datn.je3wi9v.mongodb.net/?appName=datn
spring.data.mongodb.database=test
